ARG NODEJS_VERSION="14.20.0"

FROM balenalib/%%BALENA_MACHINE_NAME%%-node:${NODEJS_VERSION}-run

WORKDIR /usr/src/app

# install node dependencies
COPY ./package.json /usr/src/app/package.json
RUN JOBS=MAX npm install --unsafe-perm --save 

COPY . /usr/src/app/
RUN chmod +x ./*.sh
RUN chmod 777 -R /usr/src/app

# Start app
CMD ["bash", "/usr/src/app/start.sh"]